name: Actualizar calendario

on:
  schedule:
    - cron: '*/5 * * * *' # cada 5 minutos (estable en GitHub)
  workflow_dispatch:

jobs:
  actualizar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install dropbox python-dotenv PyGithub

      - name: Ejecutar script
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
        run: python main.py

      - name: Subir cambios
        run: |
          git config --global user.name "bot-calendario"
          git config --global user.email "bot@github.com"

          git add eventos.ics
          git commit -m "Actualización automática calendario" || echo "Sin cambios"
          git push
